name: oye_yaaro_pec
description: A new oyeYarro application for PEC.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_database: ^3.0.4
  firebase_auth: ^0.11.1+10
  cloud_firestore: ^0.12.7 
  firebase_storage: ^3.0.3
  firebase_messaging: ^5.1.1
  firebase_core: ^0.4.0+6
  permission_handler: ^3.2.0
  shared_preferences: 0.4.3
  sqlcool: ^2.0.0
  fluttertoast: ^3.1.0
  http: ^0.12.0
  path_provider: ^1.1.2
  intl: ^0.15.7
  image_picker: ^0.6.0+17
  contacts_service: ^0.2.8
  photo_view: ^0.4.2
  share: ^0.6.2+1 
    # 0.5.3 
  audioplayers: ^0.13.1
  thumbnails: ^1.0.1
  chewie: ^0.9.6
  image : ^2.0.7
  flutter_native_image:
   git: https://github.com/btastic/flutter_native_image.git
  cached_network_image: ^1.1.1 
  flutter_staggered_grid_view: ^0.3.0
  flutter_ffmpeg: ^0.2.7
  camera: ^0.5.2+1
  gradient_bottom_navigation_bar: ^1.0.0+4
  # multi_image_picker: ^4.3.5
  vibrate: ^0.0.4
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
